# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-24 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='dob',
            field=models.DateTimeField(),
        ),
    ]
