# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-24 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170724_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Name',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.details'),
        ),
    ]
