# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-24 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_userprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.details'),
        ),
    ]
